#!/bin/sh

check_tabs()
{
    if grep -q -P '\t' "$1"; then
        echo "Tabs: $1"
        return 1
    fi

    return 0
}

check_trailing_whitespaces()
{
    if grep -q -P '[ \t]+$' "$1"; then
        echo "Trailing whitespaces: $1"
        return 1
    fi

    return 0
}

check_clang_format()
{
    suffix=$(echo "$1" | sed 's/.*\.//')

    if [ $suffix = 'c' -o $suffix = 'h' ]; then
        sum=$(cat "$1" | md5sum)
        clang_format_sum=$(clang-format --style=file "$1" | md5sum)
        if [ "$clang_format_sum" != "$sum" ]; then
            # Clang-format changed the file
            echo "Clang-format: $1"
            return 1
        fi
    fi

    return 0
}

check_cppcheck()
{
    cppcheck --quiet --error-exitcode=1 --force --enable=all \
             --suppress=missingIncludeSystem --inline-suppr src/
    # Return value of this function is a return value of the last
    # command
}

# Check all files that has some staged content
git diff --cached --name-only | {
    retcode=0

    # Individual file checks
    while read f; do
        check_tabs "$f" || retcode=1
        check_trailing_whitespaces "$f" || retcode=1
        check_clang_format "$f" || retcode=1
    done

    # Multiple file checks
    check_cppcheck || retcode=1

    exit $retcode
}
