#!/bin/sh

# Check all files that has some staged content
git diff --cached --name-only | {
    retcode=0

    while read f; do
        # Check the file for tabs
        if grep -q -P '\t' "$f"; then
            echo "Tabs: $f"
            retcode=1
        fi
        # Check the file for trailing whitespaces
        if grep -q -P '[ \t]+$' "$f"; then
            echo "Trailing whitespaces: $f"
            retcode=1
        fi

        suffix=$(echo "$f" | sed 's/.*\.//')

        # Check compliance with clang-format
        if [ $suffix = 'c' -o $suffix = 'h' ]; then
            sum=$(cat "$f" | md5sum)
            clang_format_sum=$(clang-format --style=file "$f" | md5sum)
            if [ "$clang_format_sum" != "$sum" ]; then
                # Clang-format changed the file
                echo "Clang-format: $f"
                retcode=1
            fi
        fi
    done

    exit $retcode
}
